[package]
name = "git-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
chrono = "0.4.40"
clap = { version = "4.5.32", features = ["derive"] }
flate2 = "1.1.0"
hex = "0.4.3"
ignore = "0.4.23"
sha1 = "0.10.6"
